allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@scarf/scarf': false
  unrs-resolver: true # Es necesario para la construcción de la librería unrs-resolver
overrides:
  uuid@<11.1.1: ^11.1.1
