openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /actividad:
    get:
      operationId: ActividadController_getAll
      parameters:
        - name: queryParams
          required: false
          in: query
          description: Filtros opcionales.
          schema: {}
      responses:
        '200':
          description: Actividades obtenidas.
        '404':
          description: Sin resultados.
      summary: Obtener todas las actividades
      tags: &ref_0
        - Actividad
  /actividad/{id}:
    get:
      operationId: ActividadController_getById
      parameters:
        - name: id
          required: true
          in: path
          description: ID de la actividad.
          schema:
            type: string
      responses:
        '200':
          description: Actividad obtenida.
        '404':
          description: No encontrada.
      summary: Obtener actividad por ID
      tags: *ref_0
  /auditoria/ordenadas:
    get:
      operationId: AuditoriaController_getAuditoriasOrdenadas
      parameters:
        - name: orderDirection
          required: false
          in: query
          description: Dirección (ASC o DESC).
          schema: {}
        - name: orderBy
          required: false
          in: query
          description: Campo de orden.
          schema: {}
      responses:
        '200':
          description: Auditorías obtenidas.
        '400':
          description: Parámetros inválidos.
        '500':
          description: Error interno.
      summary: Obtener auditorías ordenadas
      tags: &ref_1
        - Auditoria
  /auditoria:
    get:
      operationId: AuditoriaController_getAll
      parameters:
        - name: filter
          required: false
          in: query
          description: Filtro opcional.
          schema: {}
      responses:
        '200':
          description: Auditorías obtenidas.
        '404':
          description: Sin resultados.
      summary: Obtener todas las auditorías
      tags: *ref_1
  /auditoria/{id}:
    get:
      operationId: AuditoriaController_getById
      parameters:
        - name: id
          required: true
          in: path
          description: ID de auditoría.
          schema:
            type: string
      responses:
        '200':
          description: Auditoría obtenida.
        '404':
          description: Auditoría no encontrada.
      summary: Obtener auditoría por ID
      tags: *ref_1
  /auditor:
    get:
      operationId: AuditorController_getAll
      parameters:
        - name: queryParams
          required: false
          in: query
          description: Filtros opcionales.
          schema: {}
      responses:
        '200':
          description: Auditores obtenidos.
        '404':
          description: Sin resultados.
      summary: Obtener todos los auditores
      tags: &ref_2
        - Auditor
  /auditor/{id}:
    get:
      operationId: AuditorController_getById
      parameters:
        - name: id
          required: true
          in: path
          description: ID del auditor.
          schema:
            type: string
      responses:
        '200':
          description: Auditor obtenido.
        '404':
          description: No encontrado.
      summary: Obtener auditor por ID
      tags: *ref_2
  /cargue-masivo/auditorias:
    post:
      operationId: CargueMasivoController_cargueMasivo
      parameters: []
      requestBody:
        required: true
        description: Carga masiva de auditorías con datos en formato Base64.
        content:
          application/json:
            schema:
              type: object
              properties:
                base64data:
                  type: string
                  description: Archivo en formato Base64.
                complemento:
                  type: object
                  description: Datos complementarios.
                tipoCarga:
                  type: string
                  description: Tipo de carga.
              required:
                - base64data
                - complemento
                - tipoCarga
      responses:
        '201':
          description: Carga masiva exitosa.
        '400':
          description: Datos inválidos.
        '500':
          description: Error interno.
      summary: Carga masiva de auditorías
      tags: &ref_3
        - Cargue Masivo
  /cargue-masivo/actividades:
    post:
      operationId: CargueMasivoController_cargueMasivoActividades
      parameters: []
      requestBody:
        required: true
        description: Carga masiva de actividades con datos en formato Base64.
        content:
          application/json:
            schema:
              type: object
              properties:
                base64data:
                  type: string
                  description: Archivo en formato Base64.
                complemento:
                  type: object
                  description: Datos complementarios.
                tipoCarga:
                  type: string
                  description: Tipo de carga.
              required:
                - base64data
                - complemento
                - tipoCarga
      responses:
        '201':
          description: Carga masiva exitosa.
        '400':
          description: Datos inválidos.
        '500':
          description: Error interno.
      summary: Carga masiva de actividades
      tags: *ref_3
  /plan-auditoria:
    get:
      operationId: PlanAuditoriaController_getAll
      parameters:
        - name: filter
          required: false
          in: query
          description: Filtro opcional.
          schema: {}
      responses:
        '200':
          description: Lista obtenida con éxito.
        '404':
          description: No se encontraron planes.
      summary: Obtiene todos los planes de auditoría.
      tags: &ref_4
        - Plan Auditoría
  /plan-auditoria/{id}:
    get:
      operationId: PlanAuditoriaController_getById
      parameters:
        - name: id
          required: true
          in: path
          description: ID del plan.
          schema:
            type: string
      responses:
        '200':
          description: Plan obtenido con éxito.
        '404':
          description: No se encontró el plan.
      summary: Obtiene un plan por ID.
      tags: *ref_4
  /plan-estado:
    get:
      operationId: PlanEstadoController_getAll
      parameters:
        - name: filter
          required: false
          in: query
          description: Filtro opcional.
          schema: {}
      responses:
        '200':
          description: Lista obtenida con éxito.
        '404':
          description: No se encontraron estados.
      summary: Obtiene todos los estados de planes.
      tags: &ref_5
        - Plan Estado
  /plan-estado/{id}:
    get:
      operationId: PlanEstadoController_getById
      parameters:
        - name: id
          required: true
          in: path
          description: ID del estado del plan.
          schema:
            type: string
      responses:
        '200':
          description: Estado obtenido con éxito.
        '404':
          description: No se encontró el estado.
      summary: Obtiene un estado de plan por ID.
      tags: *ref_5
  /plantilla/{id}:
    get:
      operationId: PlantillaController_getById
      parameters:
        - name: id
          required: true
          in: path
          description: ID de la plantilla
          schema:
            type: string
      responses:
        '200':
          description: Plantilla encontrada.
      summary: Obtener plantilla por ID
      tags: &ref_6
        - Plantilla
  /plantilla/plan-trabajo/{idAuditoria}:
    get:
      operationId: PlantillaController_getPlantillaPlanTrabajo
      parameters:
        - name: idAuditoria
          required: true
          in: path
          description: ID de la auditoría
          schema:
            type: string
      responses:
        '200':
          description: Plan de trabajo encontrado.
      summary: Obtener plantilla de plan de trabajo
      tags: *ref_6
info:
  title: Plan Anual Auditoria MID
  description: API MID para la gestion de planes de auditorias, auditorias y actividades
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
