openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /plan-estado:
    get:
      operationId: PlanEstadoController_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_0
        - PlanEstado
  /plan-estado/{id}:
    get:
      operationId: PlanEstadoController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
  /plan-auditoria:
    get:
      operationId: PlanAuditoriaController_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_1
        - PlanAuditoria
  /plan-auditoria/{id}:
    get:
      operationId: PlanAuditoriaController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
  /auditoria/ordenadas:
    get:
      operationId: AuditoriaController_getAuditoriasOrdenadas
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_2
        - Auditoria
  /auditoria:
    get:
      operationId: AuditoriaController_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_2
  /auditoria/{id}:
    get:
      operationId: AuditoriaController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_2
  /actividad:
    get:
      operationId: ActividadController_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_3
        - Actividad
  /actividad/{id}:
    get:
      operationId: ActividadController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_3
  /plantilla/{id}:
    get:
      operationId: PlantillaController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: &ref_4
        - Plantilla
  /plantilla/plan-trabajo/{idAuditoria}:
    get:
      operationId: PlantillaController_getPlantillaPlanTrabajo
      parameters:
        - name: idAuditoria
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_4
  /cargue-masivo/auditorias:
    post:
      operationId: CargueMasivoController_cargueMasivo
      parameters: []
      responses:
        '201':
          description: ''
      tags: &ref_5
        - CargueMasivo
  /cargue-masivo/actividades:
    post:
      operationId: CargueMasivoController_cargueMasivoActividades
      parameters: []
      responses:
        '201':
          description: ''
      tags: *ref_5
  /auditor:
    get:
      operationId: AuditorController_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_6
        - Auditor
  /auditor/{id}:
    get:
      operationId: AuditorController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_6
info:
  title: Presupuesto Contractual API MID
  description: API
  version: '1.0'
  contact: {}
tags:
  - name: API
    description: ''
servers: []
components:
  schemas: {}
