export const environment = {
  PARAMETROS_SERVICE: process.env.PARAMETROS_SERVICE,
  PLAN_AUDITORIA_MID_PORT: process.env.PLAN_AUDITORIA_MID_PORT,
  PLAN_AUDITORIA_CRUD_SERVICE: process.env.PLAN_AUDITORIA_CRUD_SERVICE,
  PLANTILLAS_MID_SERVICE: process.env.PLANTILLAS_MID_SERVICE,
  CARGUE_MASIVO_SERVERLESS_MID: process.env.CARGUE_MASIVO_SERVERLESS_MID,
  TERCEROS_SERVICE: process.env.TERCEROS_SERVICE,
};
